apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-mount
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
